const express=require('express');
const app=express();
const path=require('path');
const fs=require('fs');
app.use('/public',express.static('public'));
app.set('views',path.join(__dirname,"./views/"));
app.set('view engine','hbs');
const env=require('dotenv');
const port=process.env.PORT || 3000;
env.config({path:"./require/config.env"});
var home=require('./route/home');
var registration=require('./route/registration');
var reg_verify=require('./route/reg_verify');
var log_verify=require('./route/log_verify');
var profile=require('./route/profile');
var logout=require('./route/logout');
var error=require('./route/error');
app.use('/',home);
app.use('/',registration);
app.use('/',reg_verify);
app.use('/',log_verify);
app.use('/',profile);
app.use('/',logout);
app.use('/',error);
app.listen(port);